name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Install Temurin distribution
        java-version: '21'       # Set the Java version to 21

    - name: Build with Maven (Skip tests)
      run: mvn clean install -DskipTests
